export default Languages = {
  languageDrawer: {
    English: "Language",
    Russian: "Язык",
    Francais: "Langue",
    Spanish: "Idioma",
    Portuguese: "Língua",
    Deutsch: "Sprache",
    Italiano: "Linguaggio",
  },
  plantsDrawer: {
    English: "Plants",
    Russian: "Растения",
    Francais: "Plantes",
    Spanish: "Plantas",
    Portuguese: "Plantas",
    Deutsch: "Pflanzen",
    Italiano: "Piante",
  },
  plants: {
    English: "Medical Plants",
    Russian: "Лекарственные растения",
    Francais: "Plantes Medicinales",
    Spanish: "Plantas Medicinales",
    Portuguese: "Plantas Medicinals",
    Deutsch: "Medizinische Pflanzen",
    Italiano: "Piante Medicinali",
  },
  plantsName: {
    English: "Common name",
    Russian: "Общее название",
    Francais: "Nom vulgaire",
    Spanish: "Nombre vulgar",
    Portuguese: "Nome vulgar",
    Deutsch: "Vulgärer name",
    Italiano: "Nome volgare",
  },
  search: {
    English: "Search",
    Russian: "Поиск",
    Francais: "Chercher",
    Spanish: "Buscar",
    Portuguese: "Procurar",
    Deutsch: "Suche",
    Italiano: "Ricerca",
  },
  plantsCategory: {
    English: "Category",
    Russian: "Категория",
    Francais: "Catègorie",
    Spanish: "Categoría",
    Portuguese: "Categoria",
    Deutsch: "Kategorie",
    Italiano: "Categoria",
  },
  plantsHistoryAndUse: {
    English: "History And Use",
    Russian: "История и Использование",
    Francais: "Histoire Et Utilisation",
    Spanish: "Historia Y Uso",
    Portuguese: "História E Uso",
    Deutsch: "Geschichte Und Verwendung",
    Italiano: "Storia E Utilizzo",
  },
  plantsDesc: {
    English: "Description Of The Plant",
    Russian: "Описание Растения",
    Francais: "Description De L'usine",
    Spanish: "Descripción De La Planta",
    Portuguese: "Descrição Da Planta",
    Deutsch: "Beschreibung Der Anlage",
    Italiano: "Descrizione Della Pianta",
  },
  plantsCurativeAction: {
    English: "Curative Action",
    Russian: "Лечебное Действие",
    Francais: "Action Curative",
    Spanish: "Acción Curativa",
    Portuguese: "Ação Curativa",
    Deutsch: "Heilwirkung",
    Italiano: "Azione Curativa",
  },
  plantsUses: {
    English: "Uses",
    Russian: "Использования",
    Francais: "Les Usages",
    Spanish: "Usos",
    Portuguese: "Usos",
    Deutsch: "Verwendet",
    Italiano: "Usi",
  },
  treatmentsDrawer: {
    English: "Treatments",
    Russian: "Лечения",
    Francais: "Traitements",
    Spanish: "Tratamientos",
    Portuguese: "Tratamentos",
    Deutsch: "Behandlungen",
    Italiano: "Trattamenti",
  },
  treatments: {
    English: "Treatments",
    Russian: "Лечение",
    Francais: "Traitements",
    Spanish: "Tratamientos",
    Portuguese: "Tratamentos",
    Deutsch: "Behandlungen",
    Italiano: "Trattamenti",
  },
  remediesDrawer: {
    English: "Simple remedies",
    Russian: "Простые средства",
    Francais: "Remèdes simples",
    Spanish: "Remedios simple",
    Portuguese: "Remédios simple",
    Deutsch: "Einfache heilmittel",
    Italiano: "Semplici rimedi",
  },
  remedies: {
    English: "Simple Remedies",
    Russian: "Простые средства",
    Francais: "Remèdes Simples",
    Spanish: "Remedios Simple",
    Portuguese: "Remédios Simple",
    Deutsch: "Einfache heilmittel",
    Italiano: "Semplici Rimedi",
  },
  pharmacyDrawer: {
    English: "Pharmacy",
    Russian: "Фармация",
    Francais: "Pharmacie",
    Spanish: "Farmacia",
    Portuguese: "Farmacia",
    Deutsch: "Apotheke",
    Italiano: "Farmacia",
  },
  pharmacy: {
    English: "Natural drugs",
    Russian: "Натуральные лекарства",
    Francais: "Mèdicaments naturel",
    Spanish: "Drogas naturales",
    Portuguese: "Drogas naturais",
    Deutsch: "Apotheke",
    Italiano: "Droghe naturali",
  },
  fruitsAndBerriesDrawer: {
    English: "Fruits and Berries",
    Russian: "Фрукты и ягоды",
    Francais: "Les Fruits et les Baies",
    Spanish: "Frutas y bayas",
    Portuguese: "Frutos e bagas",
    Deutsch: "Früchte und Beeren",
    Italiano: "Frutta e bacche",
  },
  fruitsAndBerries: {
    English: "Fruits and berries",
    Russian: "Фрукты и ягоды",
    Francais: "Les Fruits et les Baies",
    Spanish: "Frutas y bayas",
    Portuguese: "Frutos e bagas",
    Deutsch: "Früchte und beeren",
    Italiano: "Frutta e bacche",
  },
  PoisonousPlantsDrawer: {
    English: "Poisonous Plants",
    Russian: "Ядовитые растения",
    Francais: "Les Plantes Toxiques",
    Spanish: "Plantas venenosas",
    Portuguese: "Plantas Venenosas",
    Deutsch: "Giftige Pflanzen",
    Italiano: "Piante Velenose",
  },
  PoisonousPlants: {
    English: "Poisonous plants",
    Russian: "Ядовитые растения",
    Francais: "Les plantes toxiques",
    Spanish: "Plantas venenosas",
    Portuguese: "Plantas venenosas",
    Deutsch: "Giftige pflanzen",
    Italiano: "Piante velenose",
  },
  shareDrawer: {
    English: "Share with friends",
    Russian: "Поделиться с друзьями",
    Francais: "Partager avec des amis",
    Spanish: "Compartir con amigos",
    Portuguese: "Partilhar com amigos",
    Deutsch: "Mit Freunden teilen",
    Italiano: "Condividi con gli amici",
  },
  rateDrawer: {
    English: "RATE US",
    Russian: "ОЦЕНИТЬ ПРИЛОЖЕНИЕ",
    Francais: "NOTEZ L'APPLICATION",
    Spanish: "NOTA LA APLICACION",
    Portuguese: "OBSERVE O APLICATIVO",
    Deutsch: "BEACHTEN SIE DIE ANWENDUNG",
    Italiano: "NOTA L'APPLICAZIONE",
  },
  rateAppTitle: {
    English: "Rate application",
    Russian: "Оценить приложение",
    Francais: "Application de taux",
    Spanish: "Aplicación de tasa",
    Portuguese: "Taxa de aplicação",
    Deutsch: "Bewerten Sie die Anwendung",
    Italiano: "Valuta l'applicazione",
  },
  rateAppDescription: {
    English:
      "If you like this application, please take the time to rate it. It will take no more than a minute. Thanks for your support!",
    Russian:
      "Если вам нравится это приложение,пожалуйста, найдите время, чтобы оценить его. Это займет не более минуты. Спасибо за Вашу поддержку!",
    Francais:
      "Si vous aimez cette application, veuillez prendre le temps de l'évaluer. Il ne prendra pas plus d'une minute. Merci pour votre soutien!",
    Spanish:
      "Si te gusta esta aplicación, tómese el tiempo para calificarla. No tomará más de un minuto. Gracias por su apoyo!",
    Portuguese:
      "Se você gosta desta aplicação, por favor, tome o tempo para classificá-la. Não vai demorar mais do que um minuto. Obrigado pelo seu apoio!",
    Deutsch:
      "Wenn Sie diese Anwendung mögen, nehmen Sie sich bitte die Zeit, es zu bewerten. Es wird nicht länger als eine minute dauern. Vielen Dank für Ihre Unterstützung!",
    Italiano:
      "Se ti piace questa applicazione, si prega di prendere il tempo di votarla. Ci vorrà non più di un minuto. Grazie per il vostro sostegno!",
  },
  rateAskLater: {
    English: "Ask me later",
    Russian: "Спросить позже",
    Francais: "Demandez moi plus tard",
    Spanish: "Preguntar más tarde",
    Portuguese: "Pergunta-me mais tarde",
    Deutsch: "Frag mich später",
    Italiano: "Chiedimelo dopo",
  },
  rateNoThanks: {
    English: "No, thanks",
    Russian: "Нет, спасибо",
    Francais: "Non, merci",
    Spanish: "No, gracias",
    Portuguese: "Não, obrigado",
    Deutsch: "Nein, danke",
    Italiano: "No, grazie",
  },
  rateRate: {
    English: "Rate",
    Russian: "Оценить",
    Francais: "Taux",
    Spanish: "Tasa",
    Portuguese: "Taxa",
    Deutsch: "Preis",
    Italiano: "Tasso",
  },
  shareAppAndroid: {
    English:
      "I recommend Medicinal plants \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Russian:
      "Рекомендую Лекарственные растения \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Francais:
      "Je recommande Les plantes médicinales \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Spanish:
      "Recomiendo Plantas medicinales \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Portuguese:
      "Eu recomendo Plantas medicinais \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Deutsch:
      "Ich empfehle Heilpflanzen \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
    Italiano:
      "Raccomando Piante medicinali \nhttps://play.google.com/store/apps/details?id=mobi.devsteam.medicinalplants",
  },
  shareAppIOS: {
    English:
      "I recommend Medicinal plants \nhttps://www.apple.com/ios/app-store",
    Russian:
      "Рекомендую Лекарственные растения \nhttps://www.apple.com/ios/app-store",
    Francais:
      "Je recommande Les plantes médicinales \nhttps://www.apple.com/ios/app-store",
    Spanish:
      "Recomiendo Plantas medicinales \nhttps://www.apple.com/ios/app-store",
    Portuguese:
      "Eu recomendo Plantas medicinais \nhttps://www.apple.com/ios/app-store",
    Deutsch: "Ich empfehle Heilpflanzen \nhttps://www.apple.com/ios/app-store",
    Italiano:
      "Raccomando Piante medicinali \nhttps://www.apple.com/ios/app-store",
  },
  exitAppTitle: {
    English: "Exit",
    Russian: "Выход",
    Francais: "Sortie",
    Spanish: "Salida",
    Portuguese: "Saída",
    Deutsch: "Ausgang",
    Italiano: "Uscita",
  },
  exitAppDesc: {
    English: "Do you want to exit app?",
    Russian: "Вы хотите выйти из приложения?",
    Francais: "Voulez-vous quitter l'application?",
    Spanish: "¿Quieres salir de la aplicación?",
    Portuguese: "Deseja sair do aplicativo?",
    Deutsch: "Möchten Sie die App beenden?",
    Italiano: "Vuoi uscire dall'app?",
  },
  yes: {
    English: "OK",
    Russian: "Да",
    Francais: "Oui",
    Spanish: "Si",
    Portuguese: "Sim",
    Deutsch: "Ja",
    Italiano: "Sì",
  },
  cancel: {
    English: "Cancel",
    Russian: "Отмена",
    Francais: "Annuler",
    Spanish: "Cancelar",
    Portuguese: "Cancelar",
    Deutsch: "Stornieren",
    Italiano: "Annulla",
  },
};
